- repeat_handler:
    commands:
      - name: Repeat
        description: "`repeat [sentence]`: Repeats the sentence you wrote"
        regex: !ruby/regexp "/^repeat (?<sentence>.+)/i"
        action: repeat